name = "GraphIdx"
uuid = "6f20e514-06e4-11e9-04c5-39592f74a46d"
authors = ["Elias Kuthe <elias.kuthe@tu-dortmund.de>"]
version = "0.11.1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
